# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: openjdk8
before_install: mvn install:install-file -DgroupId=oracle.jdbc.OracleDriver -DartifactId=ojdbc6 -Dversion=11.2.0.4.0 -Dpackaging=jar -Dfile=ojdbc6.jar -DgeneratePom=true

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
    - $HOME/.m2